apiVersion: diengine.opendilab.org/v1alpha1
kind: DIJob
metadata:
    # name: empty8-ngu-bs2-ul98-erbm1
    # name: fourroom-icm-fourroom-with-intrinsic-logger
    #name: doorkey8-seed10
    #name: doorkey-ngu-bs2-ul298-erbm1
    #python3 /mnt/lustre/zhoutong/lodge/DI-engine/dizoo/minigrid/config/Doorkey8_icm_seed10.py
    name: zt1-csac-s-v1
spec:
  group: ding
  priorityClassName: ""
  cleanPodPolicy: "Running"
  volumes:
  - name: cache-volume
    emptyDir:
      medium: Memory
      sizeLimit: 128Mi
  volumes:
  - name: volume-tmp
    hostPath:
      path: /mnt/lustre/zhoutong
  coordinator:
    template:
      spec:
        containers:
        - name: di-container
          image: registry.sensetime.com/xlab/ding:cuda-nightly-atari
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /mnt/lustre/zhoutong
            name: volume-tmp
          env:
          - name: PYTHONUNBUFFERED
            value: "1"
          resources:
            requests:
              nvidia.com/gpu-1080ti: 1
              cpu: 25
              memory: "130Gi"
            limits:
              nvidia.com/gpu-1080ti: 1
              cpu: 25
              memory: "150Gi"
          command: ["/bin/bash", "-c",]
          args:
          - |
            export http_proxy=http://proxy.sensetime.com:3128/
            export https_proxy=http://proxy.sensetime.com:3128/
            export HTTP_PROXY=http://proxy.sensetime.com:3128/
            export HTTPS_PROXY=http://proxy.sensetime.com:3128/

            cd /mnt/lustre/zhoutong/october/DI-engine
            pip install -e . -i https://pkg.sensetime.com/repository/pypi-proxy/simple/ --trusted-host pkg.sensetime.com 
            # pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
            cd /mnt/lustre/zhoutong/october/metadrive
            pip install -e . -i https://pkg.sensetime.com/repository/pypi-proxy/simple/ --trusted-host pkg.sensetime.com 
            pip install mpire -i https://pkg.sensetime.com/repository/pypi-proxy/simple/ --trusted-host pkg.sensetime.com
            cd /mnt/lustre/zhoutong/october/xad
            pip install -e . -i https://pkg.sensetime.com/repository/pypi-proxy/simple/ --trusted-host pkg.sensetime.com 
            cd /mnt/lustre/zhoutong/october/data_xad
            python3 -u /mnt/lustre/zhoutong/october/xad/review_test/ral_env/const_sac/zt1_csac_straight.py

          ports:
          - name: di-port
            containerPort: 22270
